package com.epam.gems.parsers;

public enum GemXmlTags {
    GEMS, GEM,
    CERTIFICATE_NUMBER, NAME, EXTRACTION_PLACE,
    VISUAL_PARAMETERS, COLOR, TRANSPARENT_TYPE, STONE_PLANES,
    ORIGIN_TYPE, CARATS,
    WEIGHT, ORNAMENTAL_TYPE
}
